import org.gradle.api.DefaultTask
import org.gradle.api.tasks.Exec
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty

extension {
    name = "extensions/extension.mpe"
}

android {
    namespace = "app.template.extension"
}

val charityFrameworkDir = rootProject.layout.projectDirectory.dir("CharityFramework-Bplace")

// Builds the mobile framework bundle (dist/CharityFramework.mobile.js).
val buildCharityFramework = tasks.register<Exec>("buildCharityFramework") {
    group = "charity"
    description = "Builds the Charity Framework mobile bundle (pnpm, bun fallback)."
    workingDir = charityFrameworkDir.asFile
    val runner = providers.exec {
        commandLine("bash", "-lc", "command -v bun >/dev/null 2>&1 && echo bun || echo pnpm")
    }.standardOutput.asText.get().trim()
    commandLine(if (runner == "bun") "bun" else "pnpm", "run", "build:mobile")
    inputs.dir(charityFrameworkDir.dir("packages"))
    inputs.file(charityFrameworkDir.file("package.json"))
    inputs.file(charityFrameworkDir.file("rollup.config.mjs"))
    outputs.file(charityFrameworkDir.file("dist/CharityFramework.mobile.js"))
}

/**
 * Splits the mobile bundle into Java string constants (each well under the
 * 64KiB dex string limit) and writes build/generated/charity/
 * CharityScriptAssets.java. A String[] + runtime join keeps javac from
 * folding the concatenation back into a single oversized constant.
 */
abstract class GenerateCharityScript : DefaultTask() {
    @get:InputFile
    abstract val bundleFile: RegularFileProperty

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val js = bundleFile.get().asFile.readText()
        val dir = outputDirectory.get().asFile
        dir.mkdirs()
        dir.resolve("CharityScriptAssets.java").writeText(buildSource(js))
    }

    private fun buildSource(js: String): String {
        val chunks = js.chunked(20000)
        val out = StringBuilder()
        out.append("package app.template.extension;\n\n")
            .append("// Generated by generateCharityScript — do not edit by hand.\n")
            .append("public final class CharityScriptAssets {\n")
            .append("    private static final String[] CHUNKS = new String[] {\n")
        for (chunk in chunks) {
            out.append("        \"").append(escapeJavaString(chunk)).append("\",\n")
        }
        out.append("    };\n\n")
            .append("    public static final String BUNDLE = join(CHUNKS);\n\n")
            .append("    private static String join(String[] parts) {\n")
            .append("        StringBuilder sb = new StringBuilder();\n")
            .append("        for (String p : parts) sb.append(p);\n")
            .append("        return sb.toString();\n")
            .append("    }\n")
            .append("}\n")
        return out.toString()
    }

    private fun escapeJavaString(s: String): String {
        val out = StringBuilder()
        for (c in s) {
            when (c) {
                '\\' -> out.append("\\\\")
                '"' -> out.append("\\\"")
                '\n' -> out.append("\\n")
                '\r' -> out.append("\\r")
                '\t' -> out.append("\\t")
                else -> if (c.code < 0x20 || c.code > 0x7e) {
                    out.append("\\u").append(String.format("%04x", c.code))
                } else {
                    out.append(c)
                }
            }
        }
        return out.toString()
    }
}

val generateCharityScript = tasks.register<GenerateCharityScript>("generateCharityScript") {
    group = "charity"
    description = "Embeds dist/CharityFramework.mobile.js as Java string constants."
    dependsOn(buildCharityFramework)
    bundleFile.set(charityFrameworkDir.file("dist/CharityFramework.mobile.js"))
    outputDirectory.set(layout.buildDirectory.dir("generated/charity"))
}

// Registers build/generated/charity as a generated Java source directory for
// every variant (compiles CharityScriptAssets.java, and by extension makes
// generateCharityScript a real dependency of the Java compilation).
androidComponents {
    onVariants {
        it.sources.java?.addGeneratedSourceDirectory(generateCharityScript) { task ->
            task.outputDirectory
        }
    }
}